spring:
  profiles:
    active: sit
  datasource:
    druid:
      username: root
      password: '{cipher}186ae3a10ce744a22d672397619c4deb535a73cc453e292ba1231c4b12ef4d75'
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/testdb
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
busi:
  ops: Y  
---
spring:
  profiles: sit
  application:
    name: ms-consumer-sit
server:
  port: 38080
---
spring:
  profiles: dev
  application:
    name: ms-consumer-dev
server:
  port: 28080
---
spring:
  profiles: uat
  application:
    name: ms-consumer-uat
server:
  port: 18080
---
spring:
  profiles: prd
  application:
    name: ms-consumer-prd
server:
  port: 8080
