spring:
  profiles:
    active: sit
  datasource:
    druid:
      username: root
      password: '{cipher}186ae3a10ce744a22d672397619c4deb535a73cc453e292ba1231c4b12ef4d75'
      jdbcUrl: jdbc:mysql://47.104.128.12:3306/tuling-cloud03
      driver-class-name: com.mysql.jdbc.Driver  
busi:
  ops: Y  
---
spring:
  profiles: sit
  application:
    name: ms-consumer-sit
server:
  port: 38080
---
spring:
  profiles: dev
  application:
    name: ms-consumer-dev
server:
  port: 28080
---
spring:
  profiles: uat
  application:
    name: ms-consumer-uat
server:
  port: 18080
---
spring:
  profiles: prd
  application:
    name: ms-consumer-prd
server:
  port: 8080
